#!/usr/bin/env bash
# Dev helper: rebuild cfcli and reload its bash completion.
#
# The completion script completions/cfcli.bash is generated by build.rs during
# `cargo build`. Registering it (`complete -F`) into your CURRENT shell only
# works when this file is SOURCED:
#
#     source scripts/refresh-completions.bash
#
# If you execute it (./scripts/refresh-completions.bash) the registration
# happens in a subshell and is lost; open a new shell and `source` it there.

# Guard: this is the bash script. Sourcing it under zsh registers bash
# completion (compgen/compopt/COMPREPLY via bashcompinit) into zsh and breaks
# `cfcli` completion there. Check first, before any bash-only syntax.
if [ -n "${ZSH_VERSION:-}" ]; then
  echo "refresh-completions.bash is for bash. In zsh, source the sibling" >&2
  echo "  refresh-completions.zsh instead." >&2
  return 1 2>/dev/null || exit 1
fi

# Detect sourced vs executed (bash).
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then
  echo "Not sourced. Run instead:  source ${BASH_SOURCE[0]}" >&2
  exit 1
fi

# Resolve the repo root from this script's own location (it lives in scripts/).
CFCLI_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "==> cargo build (regenerates completions/cfcli.bash)…"
if ! ( cd "$CFCLI_DIR" && cargo build ); then
  echo "cargo build failed" >&2
  return 1
fi

# Put the dev binary first so the completion's `cfcli __complete` callbacks hit
# this build (only if not already first).
case ":$PATH:" in
  *":$CFCLI_DIR/target/debug:"*) ;;
  *) export PATH="$CFCLI_DIR/target/debug:$PATH" ;;
esac
hash -r

if grep -q '_cfcli_dynamic' "$CFCLI_DIR/completions/cfcli.bash" \
   && grep -q 'config-keys' "$CFCLI_DIR/completions/cfcli.bash"; then
  echo "==> dynamic glue present"
else
  echo "==> WARNING: dynamic glue not found — generated file may be stale" >&2
fi

# shellcheck disable=SC1091
source "$CFCLI_DIR/completions/cfcli.bash"
echo "==> completion reloaded. Try:  cfcli param set <TAB>"
