#!/usr/bin/env zsh
# Dev helper: rebuild cfcli and reload its zsh completion.
#
# The completion script `completions/_cfcli` is generated by build.rs during
# `cargo build`, then copied onto your fpath. Reloading it into your CURRENT
# shell requires dropping the cached `_cfcli` function and re-running compinit
# — that only works when this file is SOURCED:
#
#     source scripts/refresh-completions.zsh
#
# If you instead execute it (./scripts/refresh-completions.zsh) it does the
# file prep only; open a new terminal afterwards to pick up the change.

# Guard: this is the zsh script. Loading it under bash would register zsh
# completion machinery in the wrong shell. (POSIX-compatible; runs before any
# zsh-only syntax below.)
if [ -n "${BASH_VERSION:-}" ]; then
  echo "refresh-completions.zsh is for zsh. In bash, source the sibling" >&2
  echo "  refresh-completions.bash instead." >&2
  return 1 2>/dev/null || exit 1
fi

# Resolve the repo root from this script's own location (it lives in scripts/).
CFCLI_SELF="${${(%):-%x}:A}"
CFCLI_DIR="${CFCLI_SELF:h:h}"
ZFUNC_DIR="${ZFUNC_DIR:-$HOME/.zfunc}"

# --- file prep (safe whether sourced or executed) -------------------------
_cfcli_refresh_prep() {
  emulate -L zsh
  setopt local_options

  print -P "%F{cyan}==> cargo build (regenerates completions/_cfcli)…%f"
  if ! ( cd "$CFCLI_DIR" && cargo build ); then
    print -P "%F{red}cargo build failed%f"
    return 1
  fi

  mkdir -p "$ZFUNC_DIR"
  if ! cp "$CFCLI_DIR/completions/_cfcli" "$ZFUNC_DIR/_cfcli"; then
    print -P "%F{red}copy failed%f"
    return 1
  fi
  print -P "%F{cyan}==> copied to $ZFUNC_DIR/_cfcli%f"

  # Confirm the '=' wiring is in the copied file (catches a stale generate).
  if grep -q 'compadd -U -Q -S' "$ZFUNC_DIR/_cfcli" \
     && grep -q '_cfcli_param_set()' "$ZFUNC_DIR/_cfcli"; then
    print -P "%F{green}==> '=' wiring present%f"
  else
    print -P "%F{yellow}==> WARNING: '=' wiring NOT found — generated file may be stale%f"
  fi

  # Clear cached compdumps so compinit rebuilds from the new file.
  rm -f ~/.zcompdump*(N) 2>/dev/null
  if [[ -n "$ZSH_CACHE_DIR" ]]; then
    rm -f "$ZSH_CACHE_DIR"/.zcompdump*(N) 2>/dev/null
  fi
  return 0
}

_cfcli_refresh_prep
_cfcli_refresh_rc=$?
unfunction _cfcli_refresh_prep 2>/dev/null

if (( _cfcli_refresh_rc != 0 )); then
  unset _cfcli_refresh_rc CFCLI_SELF CFCLI_DIR ZFUNC_DIR
  return 1 2>/dev/null || exit 1
fi
unset _cfcli_refresh_rc

# Make sure the dir is on fpath (affects the current shell when sourced).
if (( ${fpath[(Ie)$ZFUNC_DIR]} == 0 )); then
  fpath=("$ZFUNC_DIR" $fpath)
fi

# --- reload current shell (only possible when sourced) --------------------
if [[ "$ZSH_EVAL_CONTEXT" == *:file* ]]; then
  unfunction _cfcli 2>/dev/null
  autoload -Uz compinit && compinit -u
  print -P "%F{green}==> completion reloaded. Try:  cfcli param set <TAB>%f"
else
  print -P "%F{yellow}==> file prep done, but not sourced.%f"
  print -P "%F{yellow}    Reload with:  source $0%f"
  print -P "%F{yellow}    …or just open a new terminal.%f"
fi

unset CFCLI_SELF CFCLI_DIR ZFUNC_DIR
